ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS owner_id VARCHAR(160);

CREATE TABLE charging_reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id VARCHAR(160) NOT NULL,
  vehicle_id BIGINT NOT NULL REFERENCES vehicles(id),
  station_id BIGINT NOT NULL,
  station_name VARCHAR(160) NOT NULL,
  scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
  target_soc INTEGER NOT NULL,
  estimated_cost INTEGER NOT NULL,
  status VARCHAR(24) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE service_bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id VARCHAR(160) NOT NULL,
  vehicle_id BIGINT NOT NULL REFERENCES vehicles(id),
  center_name VARCHAR(160) NOT NULL,
  service_type VARCHAR(160) NOT NULL,
  scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
  estimated_cost INTEGER NOT NULL,
  status VARCHAR(24) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE handovers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id VARCHAR(160) NOT NULL,
  vehicle_id BIGINT NOT NULL REFERENCES vehicles(id),
  transfer_code VARCHAR(32) NOT NULL UNIQUE,
  buyer_email_masked VARCHAR(160) NOT NULL,
  status VARCHAR(32) NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id VARCHAR(160) NOT NULL,
  title VARCHAR(180) NOT NULL,
  message VARCHAR(320) NOT NULL,
  category VARCHAR(32) NOT NULL,
  read BOOLEAN NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id VARCHAR(160) NOT NULL,
  action VARCHAR(80) NOT NULL,
  resource_type VARCHAR(80) NOT NULL,
  resource_id VARCHAR(80) NOT NULL,
  detail VARCHAR(500) NOT NULL,
  signature VARCHAR(80) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_charging_actor ON charging_reservations(actor_id, created_at);
CREATE INDEX idx_service_actor ON service_bookings(actor_id, created_at);
CREATE INDEX idx_handover_actor ON handovers(actor_id, updated_at);
CREATE INDEX idx_notifications_actor ON notifications(actor_id, created_at);
CREATE INDEX idx_audit_created ON audit_logs(created_at);
