CREATE TABLE vehicle_journal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id BIGINT NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  category VARCHAR(24) NOT NULL,
  title VARCHAR(100) NOT NULL,
  note VARCHAR(500) NOT NULL,
  entry_date DATE NOT NULL,
  amount BIGINT,
  odometer INTEGER,
  status VARCHAR(16) NOT NULL,
  archived_status VARCHAR(16),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_vehicle_journal_vehicle_date ON vehicle_journal(vehicle_id, entry_date);
